# Project Settings
---

# Example Project
jobexample:
    jobname: jobexample
    shortname: jex
    jobtype: film
    sequences:
        - name: AAA
          shots:
            - name: aaa
            - name: aab
            - name: aac
        - name: BBB
          shots:
            - name: bba
            - name: bbb
            - name: bbc
        - name: test
          shots:
            - name: color
            - name: comp
            - name: explosion

